"""add user_segments table

Revision ID: 20250801_190200
Revises:
Create Date: 2025-08-01 19:02:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250801_190200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rfm_group', sa.String(length=50), nullable=True),
    sa.Column('ltv_score', sa.Float(), nullable=True),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_segments_id'), 'user_segments', ['id'], unique=False)
    op.create_index(op.f('ix_user_segments_rfm_group'), 'user_segments', ['rfm_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_segments_rfm_group'), table_name='user_segments')
    op.drop_index(op.f('ix_user_segments_id'), table_name='user_segments')
    op.drop_table('user_segments')
    # ### end Alembic commands ###
