"""add_site_id_password_phone_fields

Revision ID: 3e7905876b33
Revises: 4c54145429eb
Create Date: 2025-07-26 10:20:56.265630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3e7905876b33'
down_revision: Union[str, None] = '4c54145429eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('payout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.drop_index(op.f('ix_age_verification_records_id'), table_name='age_verification_records')
    op.drop_table('age_verification_records')
    op.add_column('adult_content', sa.Column('required_rank', sa.String(length=20), nullable=False))
    op.alter_column('user_rewards', 'source_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_rewards_awarded_at'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_reward_type'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_user_id'), table_name='user_rewards')
    op.alter_column('user_segments', 'rfm_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_segments', 'risk_profile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_segments_rfm_group'), table_name='user_segments')
    op.drop_index(op.f('ix_user_segments_risk_profile'), table_name='user_segments')
    op.drop_index(op.f('ix_user_segments_user_id'), table_name='user_segments')
    op.drop_column('user_segments', 'last_updated')
    op.drop_column('user_segments', 'recency_score')
    op.drop_column('user_segments', 'frequency_score')
    op.drop_column('user_segments', 'monetary_score')
    op.drop_column('user_segments', 'streak_count')
    op.add_column('users', sa.Column('site_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'invite_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('users', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text('("STANDARD")'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=True)
    op.drop_column('users', 'segment_label')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('segment_label', sa.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.alter_column('users', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('("STANDARD")'))
    op.alter_column('users', 'invite_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'site_id')
    op.add_column('user_segments', sa.Column('streak_count', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('monetary_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('frequency_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('recency_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('last_updated', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_user_segments_user_id'), 'user_segments', ['user_id'], unique=1)
    op.create_index(op.f('ix_user_segments_risk_profile'), 'user_segments', ['risk_profile'], unique=False)
    op.create_index(op.f('ix_user_segments_rfm_group'), 'user_segments', ['rfm_group'], unique=False)
    op.alter_column('user_segments', 'risk_profile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_segments', 'rfm_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_rewards_user_id'), 'user_rewards', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_rewards_reward_type'), 'user_rewards', ['reward_type'], unique=False)
    op.create_index(op.f('ix_user_rewards_awarded_at'), 'user_rewards', ['awarded_at'], unique=False)
    op.alter_column('user_rewards', 'source_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('adult_content', 'required_rank')
    op.create_table('age_verification_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('verification_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('verification_data', sqlite.JSON(), nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_age_verification_records_id'), 'age_verification_records', ['id'], unique=False)
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
